mime handler improvements

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -19,6 +19,40 @@ before_script:
 variables:
   GIT_SUBMODULE_STRATEGY: recursive
 
+download_mime_handlers:
+  stage: test
+  image: debian:bookworm
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "push"
+  artifacts:
+    paths:
+      - sosse/mime_handlers.json
+  script:
+    - apt update && apt install -y curl jq unzip
+    - |
+      if [ "$CI_COMMIT_TAG" != "" ]; then
+        PLUGINS_REF="$CI_COMMIT_TAG"
+      elif [ "$CI_COMMIT_REF_NAME" = "stable" ]; then
+        PLUGINS_REF="stable"
+      elif [[ "$CI_COMMIT_REF_NAME" =~ ^branch-[0-9]+\.[0-9]+$ ]]; then
+        PLUGINS_REF="$CI_COMMIT_REF_NAME"
+      else
+        PLUGINS_REF="main"
+      fi
+      echo "Downloading mime handlers from sosse-plugins ref: $PLUGINS_REF"
+    - >
+      curl -L
+      "https://gitlab.com/biolds1/sosse-plugins/-/jobs/artifacts/$PLUGINS_REF/download?job=generate_plugins"
+      --output plugins_artifact.zip ||
+      (echo "Failed to download from ref $PLUGINS_REF, falling back to main" &&
+      curl -L
+      "https://gitlab.com/biolds1/sosse-plugins/-/jobs/artifacts/main/download?job=generate_plugins"
+      --output plugins_artifact.zip)
+    - unzip plugins_artifact.zip
+    - mv plugins.json sosse/mime_handlers.json
+    - echo "Downloaded mime handlers:"
+    - head -n 20 sosse/mime_handlers.json
+
 unit_tests:
   image: biolds/sosse:pip-test
   parallel: 3
@@ -42,6 +76,8 @@ unit_tests:
 
 manage_cmd_tests:
   image: biolds/sosse:pip-test
+  needs:
+    - download_mime_handlers
   artifacts:
     when: always
     paths:
@@ -58,6 +94,7 @@ manage_cmd_tests:
     - /tmp/sudo_sosse migrate || failed=1
     - /tmp/sudo_sosse load_se tests/opensearch.xml || failed=1
     - /tmp/sudo_sosse update_se || failed=1
+    - /tmp/sudo_sosse update_mime || failed=1
     - /tmp/sudo_sosse shell -c 'from django.contrib.auth.models import User; User.objects.all().delete()' || failed=1
     - /tmp/sudo_sosse default_admin || failed=1
     - /tmp/sudo_sosse generate_secret || failed=1
@@ -113,6 +150,7 @@ coverage_report:
     - if: $CI_PIPELINE_SOURCE == "push"
   needs:
     - doc_code_extract
+    - download_mime_handlers
   artifacts:
     when: always
     paths:
@@ -285,6 +323,7 @@ pip_pkg:
     - functional_docs_chromium
     - functional_docs_firefox
     - static_checks
+    - download_mime_handlers
   script:
     - sed -e "s/^SOSSE_VERSION_TAG = .*/SOSSE_VERSION_TAG = '${CI_COMMIT_TAG/v/}'/" -i sosse/settings.py
     - sed -e "s/^SOSSE_VERSION_COMMIT = .*/SOSSE_VERSION_COMMIT = '${CI_COMMIT_SHORT_SHA}'/" -i sosse/settings.py
@@ -306,6 +345,7 @@ debian_pkg:
     - functional_docs_chromium
     - functional_docs_firefox
     - static_checks
+    - download_mime_handlers
   artifacts:
     paths:
       - deb/*.deb
@@ -347,7 +387,7 @@ doc_test_debian:
   script:
     - mv deb/*.deb /tmp/
     - apt update
-    - apt install -y make jq
+    - apt install -y make jq sudo
     - make _doc_test_debian
 
 doc_test_pip:
@@ -361,7 +401,7 @@ doc_test_pip:
   script:
     - mv dist/*.whl /tmp/
     - apt update
-    - apt install -y make jq
+    - apt install -y make jq sudo
     - make _doc_test_pip
 
 .debian_pkg_check: &debian_pkg_check
@@ -377,6 +417,7 @@ doc_test_pip:
       - log/*
   needs:
     - doc_code_extract
+    - download_mime_handlers
     - debian_pkg
   script:
     - apt update
@@ -423,6 +464,7 @@ debian_pkg_check_firefox_docs:
       - log/*
   needs:
     - doc_code_extract
+    - download_mime_handlers
     - pip_pkg
   script:
     - make _pip_pkg_functional_tests
@@ -506,6 +548,8 @@ rebuild_docker:
   needs:
     - job: rebuild_upgrade_check
       artifacts: true
+    - job: download_mime_handlers
+      artifacts: true
   rules:
     - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "stable"
     - if: $CI_PIPELINE_SOURCE == "push"
@@ -562,6 +606,8 @@ rebuild_unit_tests:
   image: "registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID"
   needs:
     - job: rebuild_docker
+    - job: download_mime_handlers
+      artifacts: true
   rules:
     - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "stable"
     - if: $CI_PIPELINE_SOURCE == "push"
@@ -577,7 +623,8 @@ rebuild_unit_tests:
     - "/etc/init.d/postgresql start ||:"
     - "until pg_isready; do sleep 1; done"
     - apt-get update
-    - apt-get install -y rsync git curl
+    - apt-get install -y rsync git curl jq
+    - 'jq -r ".[].dependencies[]?" sosse/mime_handlers.json | sort -u | xargs apt install -y'
     - /run.sh &
     - echo -e "#!/bin/bash\nexec /venv/bin/python3 -m sosse.sosse_admin \"\$@\"" > sosse-admin.sh
     - chmod 755 sosse-admin.sh
@@ -585,6 +632,7 @@ rebuild_unit_tests:
     - until curl --silent --fail http://127.0.0.1/ > /dev/null; do sleep 1; done
     - 'sed -e "s#python3#/venv/bin/python3#" -i ./tests/test_app.sh'
     - mkdir -p /var/lib/sosse/screenshots && git clone --depth=1 https://github.com/GurvanKervern/dummy-static-website /var/lib/sosse/screenshots/website
+    - curl https://gitlab.com/biolds1/sosse-plugins/-/raw/main/mime/image-metadata/test/img-meta.png > /var/lib/sosse/screenshots/img-meta.png
     - chown www-data:www-data -R /var/lib/sosse/screenshots
     - make _rf_functional_$TEST_SUITE || failed=1
     - mv /var/log/sosse log
